name: "Validate & Build"

on:
 workflow_call:

jobs:
 Sanity:
  name: Build
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v4

   - name: Install pnpm ğŸ“¥
     uses: pnpm/action-setup@v4
     with:
      version: latest

   - name: Install Node.js ğŸ“¥
     uses: actions/setup-node@v4
     with:
      cache: pnpm
      node-version: latest

   - name: Install dependencies ğŸ“¥
     run: pnpm install

   - name: Build Binaries
     run: pnpm run build

   - name: Zip Build Output
     run: zip -r ./luna.zip ./dist

   - name: Upload Build Artifact
     uses: actions/upload-artifact@v4
     with:
      name: luna-artifacts
      path: ./luna.zip
